trigger:
  branches:
    include:
      - main

variables:
- group: terraform-secrets-dev
- name: svc
  value: practice-connection
- name: workingDir
  value: $(Build.SourcesDirectory)/Practice_Infra_LandingZone/envs/dev
- name: backendRg
  value: practice-rg-001
- name: stgname
  value: tfstatestgdev001
- name: containername
  value: tfstate
- name: statefile
  value: dev.terraform.tfstate

stages:

# =================== BUILD STAGE ===================
- stage: Build
  displayName: "Build Stage: Init, Validate, Plan"
  jobs:

  - job: InitJob
    displayName: "Terraform Init"
    pool:
      name: practice-pipeline-pool
    steps:
    - script: terraform version
      displayName: "Check Terraform Version"

    - task: TerraformTaskV3@3
      inputs:
        provider: azurerm
        command: init
        workingDirectory: "$(workingDir)"
        backendServiceArm: "$(svc)"
        ensureBackend: true
        backendAzureRmResourceGroupName: "$(backendRg)"
        backendAzureRmStorageAccountName: "$(stgname)"
        backendAzureRmContainerName: "$(containername)"
        backendAzureRmKey: "$(statefile)"

  - job: ValidateJob
    displayName: "Terraform Validate"
    dependsOn: InitJob
    pool:
      name: practice-pipeline-pool
    steps:
    - task: TerraformTaskV3@3
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: "$(workingDir)"

  - job: PlanJob
    displayName: "Terraform Plan"
    dependsOn: ValidateJob
    pool:
      name: practice-pipeline-pool
    steps:

    - task: TerraformTaskV3@3
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: "$(workingDir)"
        environmentServiceNameAzureRM: "$(svc)"
        commandOptions: >
          -input=false
          -out=tfplan
          -lock-timeout=120s

    - publish: $(workingDir)/tfplan
      artifact: tfplan-artifact
      displayName: "Publish Terraform Plan"


# =================== RELEASE STAGE ===================
- stage: Release
  displayName: "Release Stage: Approval -> Apply"
  dependsOn: Build
  jobs:

  - job: ManualApproval
    displayName: "Manual Validation"
    pool: server
    steps:
    - task: ManualValidation@1
      inputs:
        instructions: "Approve this Terraform deployment"
        notifyUsers: "adhiraaj22@gmail.com"

  - job: ApplyJob
    displayName: "Terraform Apply"
    dependsOn: ManualApproval
    pool:
      name: practice-pipeline-pool
    steps:

    - download: current
      artifact: tfplan-artifact
      displayName: "Download Plan"

    - script: terraform init -input=false
      workingDirectory: "$(workingDir)"
      displayName: "Terraform Init (Apply Stage)"

    - script: terraform apply -input=false -auto-approve tfplan
      workingDirectory: "$(workingDir)"
      displayName: "Terraform Apply"
