trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  name: practice-pipeline-pool

variables:
- group: terraform-secrets-dev
- name: svc
  value: practice-connection
- name: backendRg
  value: practice-rg-001
- name: stgname
  value: tfstatestgdev001
- name: containername
  value: tfstate
- name: statefile
  value: dev.terraform.tfstate
- name: workingDir
  value: $(System.DefaultWorkingDirectory)/Practice_Infra_LandingZone/envs/dev

stages:

#=================================================
# BUILD - INIT, VALIDATE, PLAN, PUBLISH ARTIFACT
#=================================================
- stage: Build
  displayName: "Terraform Build (Init, Validate, Plan)"
  jobs:

    - job: TerraformPlanJob
      displayName: Terraform Init, Validate & Plan
      steps:

        # Terraform Install
        - task: TerraformInstaller@1
          displayName: "Install Terraform"
          inputs:
            terraformVersion: latest

        # Terraform Init
        - task: TerraformTaskV4@4
          displayName: "Terraform Init"
          inputs:
            provider: azurerm
            command: init
            workingDirectory: "$(workingDir)"
            backendServiceArm: "$(svc)"
            ensureBackend: true
            backendAzureRmResourceGroupName: "$(backendRg)"
            backendAzureRmStorageAccountName: "$(stgname)"
            backendAzureRmContainerName: "$(containername)"
            backendAzureRmKey: "$(statefile)"

        # Terraform Validate
        - task: TerraformTaskV4@4
          displayName: "Terraform Validate"
          inputs:
            provider: azurerm
            command: validate
            workingDirectory: "$(workingDir)"

        # Terraform Plan
        - task: TerraformTaskV4@4
          displayName: "Terraform Plan"
          inputs:
            provider: azurerm
            command: plan
            workingDirectory: "$(workingDir)"
            environmentServiceNameAzureRM: "$(svc)"
            commandOptions: >
              -input=false
              -var "vm_username=$(vm_username)"
              -var "vm_password=$(vm_password)"
              -var "sql_username=$(sql_username)"
              -var "sql_password=$(sql_password)"
              -out=tfplan
              -detailed-exitcode
              -lock-timeout=120s

        # Publish plan artifact
        - publish: $(workingDir)/tfplan
          artifact: tfplan-artifact
          displayName: "Publish Terraform Plan Artifact"


#=================================================
# RELEASE - MANUAL APPROVAL + APPLY
#=================================================
- stage: Release
  displayName: "Terraform Release (Manual Approval + Apply)"
  dependsOn: Build
  jobs:

    - job: ManualValidation
      displayName: "Manual Approval Before Apply"
      pool: server
      steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: "adhiraaj22@gmail.com"

    - job: TerraformApply
      displayName: "Terraform Apply"
      dependsOn: ManualValidation
      pool:
        name: practice-pipeline-pool
      steps:

        # Install Terraform again
        - task: TerraformInstaller@1
          displayName: "Install Terraform"
          inputs:
            terraformVersion: latest

        # Download artifact
        - download: current
          artifact: tfplan-artifact

        # Terraform Init
        - task: TerraformTaskV4@4
          displayName: "Terraform Init (Apply Stage)"
          inputs:
            provider: azurerm
            command: init
            workingDirectory: "$(workingDir)"
            backendServiceArm: "$(svc)"
            ensureBackend: true
            backendAzureRmResourceGroupName: "$(backendRg)"
            backendAzureRmStorageAccountName: "$(stgname)"
            backendAzureRmContainerName: "$(containername)"
            backendAzureRmKey: "$(statefile)"

        # Terraform Apply
        - task: TerraformTaskV4@4
          displayName: "Terraform Apply"
          inputs:
            provider: azurerm
            command: apply
            workingDirectory: "$(workingDir)"
            environmentServiceNameAzureRM: "$(svc)"
            commandOptions: >
              -input=false
              -auto-approve
