trigger:
  branches:
    include:
      - main

variables:
- group: terraform-secrets-dev
- name: svc
  value: practice-connection
- name: workingDir
  value: $(System.DefaultWorkingDirectory)/azure_practice_infra/Practice_Infra_LandingZone/envs/dev
- name: backendRg
  value: practice-rg-001
- name: stgname
  value: tfstatestgdev001
- name: containername
  value: tfstate
- name: statefile
  value: dev.terraform.tfstate

stages:

# =================== BUILD (Self Hosted) ===================
- stage: Build
  displayName: "Build: Init + Validate + Plan"
  jobs:
  - job: TerraformBuild
    displayName: "Terraform Build"
    pool:
      name: practice-pipeline-pool
      demands:
      - Agent.Name -equals practice-agent

    steps:

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: latest

    - task: TerraformTaskV3@3
      displayName: "Terraform Init"
      inputs:
        provider: azurerm
        command: init
        workingDirectory: "$(workingDir)"
        backendServiceArm: "$(svc)"
        ensureBackend: true
        backendAzureRmResourceGroupName: "$(backendRg)"
        backendAzureRmStorageAccountName: "$(stgname)"
        backendAzureRmContainerName: "$(containername)"
        backendAzureRmKey: "$(statefile)"

    - task: TerraformTaskV3@3
      displayName: "Terraform Validate"
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: "$(workingDir)"

    - task: TerraformTaskV3@3
      displayName: "Terraform Plan"
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: "$(workingDir)"
        environmentServiceNameAzureRM: "$(svc)"
        commandOptions: >
          -input=false
          -var "vm_username=$(vm_username)"
          -var "vm_password=$(vm_password)"
          -var "sql_username=$(sql_username)"
          -var "sql_password=$(sql_password)"
          -out=tfplan
          -lock-timeout=120s

    - publish: $(workingDir)/tfplan
      artifact: tfplan-artifact


# =================== RELEASE (Hosted + Self Hosted) ===================
- stage: Release
  displayName: "Release: Approval → Apply"
  dependsOn: Build
  jobs:

  # Hosted for Manual Approval only
  - job: ManualApproval
    displayName: "Manual Validation"
    pool: server
    steps:
    - task: ManualValidation@1
      inputs:
        instructions: "Approve to deploy infra"
        notifyUsers: "adhiraaj22@gmail.com"

  # Self-hosted for Apply
  - job: TerraformApplyJob
    displayName: "Terraform Apply"
    dependsOn: ManualApproval
    pool:
      name: practice-pipeline-pool
      demands:
      - Agent.Name -equals practice-agent

    steps:

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: latest

    - download: current
      artifact: tfplan-artifact

    - task: TerraformTaskV3@3
      displayName: "Terraform Init (Apply Stage)"
      inputs:
        provider: azurerm
        command: init
        workingDirectory: "$(workingDir)"
        backendServiceArm: "$(svc)"
        ensureBackend: true
        backendAzureRmResourceGroupName: "$(backendRg)"
        backendAzureRmStorageAccountName: "$(stgname)"
        backendAzureRmContainerName: "$(containername)"
        backendAzureRmKey: "$(statefile)"

    - task: TerraformTaskV3@3
      displayName: "Terraform Apply"
      inputs:
        provider: azurerm
        command: apply
        workingDirectory: "$(workingDir)"
        environmentServiceNameAzureRM: "$(svc)"
        commandOptions: >
          -input=false
          -auto-approve
          -var "vm_username=$(vm_username)"
          -var "vm_password=$(vm_password)"
          -var "sql_username=$(sql_username)"
          -var "sql_password=$(sql_password)"
          tfplan
