trigger:
 branches:
   include:
     - main
     - feature/*
     
pool:
  name: practice-pipeline-pool

variables:
  svc: 'practice-connection'
  stgname: 'tfstatestgdev001'
  containername: 'tfstate'
  statefile: 'dev.terraform.tfstate'
  workingDir: '$(System.DefaultWorkingDirectory)/envs/dev'


stages:
  - stage: Build
    jobs:
      - job: terraforminitandplan
        displayName: Terraform Init, Validate & Plan
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDir)'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: '$(svc)'
              backendAzureRmStorageAccountName: '$(stgname)'
              backendAzureRmContainerName: '$(containername)'
              backendAzureRmKey: '$(statefile)'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(workingDir)'
          
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: '$(svc)'
              workingDirectory: '$(workingDir)'
          
  - stage: Release
    dependsOn: Build
    displayName: Release
    jobs:  
      - job: ManualValidation
        displayName: manual validation
        pool: server
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: 'adhiraaj22@gmail.com'
     
      - job: TerraformApply
        displayName: Terraform Apply
        dependsOn: ManualValidation
        pool: practice-pipeline-pool
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDir)'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: '$(svc)'
              backendAzureRmStorageAccountName: '$(stgname)'
              backendAzureRmContainerName: '$(containername)'
              backendAzureRmKey: '$(statefile)'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(workingDir)'
              environmentServiceNameAzureRM: '$(svc)'   
