trigger:
  branches:
    include:
      - main

variables:
- group: terraform-secrets-dev

pool: practice-pipeline-pool

stages:
  - stage: Build
    displayName: "Build"
    jobs:
      - job: initvalidateandplanjob
        displayName: "Terraform Init, Validate & Plan"
        steps:
          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/envs/dev'
              backendServiceArm: 'practice-connection'
              backendAzureRmStorageAccountName: 'tfstatestgdev001'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev.terraform.tfstate'

          - task: TerraformTask@5
            displayName: "Terraform Validate"
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/envs/dev'

          - task: TerraformTask@5
            displayName: "Terraform Plan"
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/envs/dev'
              environmentServiceNameAzureRM: 'practice-connection'
              commandOptions: '-detailed-exitcode -lock=false'

  - stage: Release
    displayName: "Release"
    dependsOn: Build
    jobs:
      - job: manualvalidation
        displayName: "Manual Validation"
        pool: server
        steps:
          - task: ManualValidation@1
            inputs:
              notifyUsers: 'adhiraaj22@gmail.com'
              approvers: 'Adhiraaj'

      - job: applyjob
        displayName: "Terraform Apply"
        dependsOn: manualvalidation
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/envs/dev'
              commandOptions: '-auto-approve'
              environmentServiceNameAzureRM: 'practice-connection'
